config/routes.rb
Rails.application.routes.draw do
  root "promises#index"
  resources :promises, only: [:index] do
    collection do
      post :check
    end
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :promises
end

app/models/promise.rb
class Promise < ActiveRecord::Base
  belongs_to :party

  def self.generate_answers(answers)
    answers.map do |party,hash|
      if party != "undefined"
        party_name = convert_to_uppercase_with_spaces(party)

        score = hash.select do |index, id|
          promise = Promise.find(id)
          party_name == promise.party.name
        end.to_a.count

        number_of_answers = hash.count

        {party: party_name, score: score, total: number_of_answers}
      end
    end.compact
  end

  private

  def self.convert_to_uppercase_with_spaces(name)
    name.camelize.underscore.split('_').collect{|c| c.capitalize}.join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/promises_controller.rb
class PromisesController < ApplicationController

  def index
    # @promises = Promise.includes(:party).all
    @promises = Party.all.map { |party| party.promises.sample(5) }.flatten.shuffle
    
    respond_to do |format|
      format.html
      format.json { render json: @promises, root: false }
    end
  end

  def check
    @scores = Promise.generate_answers(params[:promises])
    render json: @scores, root: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/promises_helper.rb
module PromisesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Doyouknowyourparty
    %link{:href => "http://fonts.googleapis.com/css?family=Vollkorn:700italic,400", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:src => "//code.jquery.com/ui/1.11.4/jquery-ui.js"}
    = csrf_meta_tags
  %body
    = yield

    %h1 How well do you know your party?

    = form_tag check_promises_path, method: :post, id:"promises" do
      
      .column
        %h2 Labour
        %ul#labour.sortable
      
      .column
        %h2 Conservatives
        %ul#conservative.sortable

      .column
        %h2 Liberal Democrats
        %ul#liberal_democrats.sortable

      .column
        %h2 Green
        %ul#green.sortable

      = submit_tag "Check your knowledge"

    %footer
      &copy; 2015. A hack made a 5am by Alex Chin. View on
      = link_to "Github", "https://github.com/alexpchin/doyouknowyourparty"
      = "."